"""The Local LLM Skeptic Agent for epigraphic and statistical critique."""

from typing import Dict, Any, Optional
from phaistos.core.provenance import ProvenanceCategory, ProvenanceRecord
from phaistos.decipherment.models import DeciphermentResult
from phaistos.llm.client import OllamaClient


SKEPTIC_SYSTEM_PROMPT = """You are the Skeptic in the Phaistos Disc Computational Laboratory.
Your role is to rigorously challenge claims, prevent statistical self-deception, and uncover hidden assumptions in proposed decipherments.
Follow the critical epigraphic principles of Yves Duhoux ('How Not to Decipher the Phaistos Disc'):
1. An undeciphered corpus of 241 signs cannot be read reliably without a bilingual or external crib.
2. Unicity distance mathematically guarantees that unconstrained phonetic substitution fits random noise.
3. A meaningful-looking translation is NEVER evidence of correctness.
4. Any hypothesis that fails to beat frequency-preserving randomized shuffles is rejected immediately.

When presented with an experiment result:
- Critique the methodology and assumptions.
- Point out what contradicts the claim in archaeological and linguistic literature.
- Propose an explicit falsification or control test.
- Keep your review concise, direct, and scientifically rigorous.
"""


def conduct_skeptic_review(
    result: DeciphermentResult,
    client: Optional[OllamaClient] = None,
    model: Optional[str] = None,
) -> ProvenanceRecord[str]:
    """
    Run an automated Skeptic review on an experiment result using local Ollama.
    Wraps response strictly in ProvenanceCategory.MODEL_INFERENCE.
    """
    llm_client = client or OllamaClient()

    prompt = f"""Evaluate the following decipherment experiment result:

Hypothesis ID: {result.hypothesis_id}
Target Language: {result.target_language}
Observed Phonotactic Score: {result.observed_score:.2f}
Shuffled Control Score (μ ± σ): {result.null_mean_score:.2f} ± {result.null_std_score:.2f}
Z-Score vs Random Noise: {result.z_score:+.2f}
Empirical p-value: {result.p_value:.4f}
Shannon Unicity Expansion Required: {result.unicity_ratio:.1f}x
Current Status: {'FALSIFIED' if result.is_falsified else 'UNDERDETERMINED'}
Skeptic Ruling: {result.skeptic_verdict}

Known Contradictions: {', '.join(result.contradictions) if result.contradictions else 'None documented'}

Sample Transliteration:
{result.sample_transliteration}

Provide a concise, 4-point Skeptic review:
1. Methodological Vulnerability
2. Hidden Assumptions
3. Academic & Epigraphic Contradictions
4. Recommended Falsification Test
"""

    if not llm_client.is_available():
        review_text = (
            f"SKEPTIC REVIEW (Deterministic Fallback - Ollama Offline):\n"
            f"1. Methodological Vulnerability: The Z-score of {result.z_score:+.2f} indicates that the "
            f"candidate mapping fails to separate from random frequency-preserving shuffles.\n"
            f"2. Hidden Assumptions: Assumes unverified Linear A/B phonetic values apply to Phaistos glyphs.\n"
            f"3. Academic Contradictions: Duhoux (2000) demonstrated that with 241 signs, unconstrained phonetic "
            f"substitutions produce spurious Greek, Semitic, or Luwian translations from noise.\n"
            f"4. Recommended Falsification Test: Permute sign mappings across 1,000 randomized control corpora."
        )
    else:
        messages = [
            {"role": "system", "content": SKEPTIC_SYSTEM_PROMPT},
            {"role": "user", "content": prompt},
        ]
        try:
            review_text = llm_client.generate_chat(messages, model=model, temperature=0.2)
        except Exception as e:
            review_text = (
                f"SKEPTIC REVIEW (Fallback — Ollama notice: {e}):\n"
                f"1. Methodological Vulnerability: The Z-score of {result.z_score:+.2f} indicates that the "
                f"candidate mapping fails to separate from random frequency-preserving shuffles.\n"
                f"2. Hidden Assumptions: Assumes unverified Linear A/B phonetic values apply to Phaistos glyphs.\n"
                f"3. Academic Contradictions: Duhoux (2000) demonstrated that with 241 signs, unconstrained phonetic "
                f"substitutions produce spurious Greek, Semitic, or Luwian translations from noise.\n"
                f"4. Recommended Falsification Test: Permute sign mappings across 1,000 randomized control corpora."
            )

    return ProvenanceRecord(
        data=review_text,
        category=ProvenanceCategory.MODEL_INFERENCE,
        source_ref=f"local_llm_skeptic:{model or llm_client.default_model}",
        confidence=0.9,
        notes="Automated critical review generated by local LLM agent",
    )
